"use client"

import { useState, useEffect } from "react"

interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

const translations: Translations = {
  ko: {
    // 공통
    home: "홈",
    community: "커뮤니티",
    files: "파일",
    mypage: "마이페이지",
    save: "저장",
    cancel: "취소",
    back: "뒤로",
    edit: "편집",
    delete: "삭제",
    create: "만들기",
    search: "검색",
    settings: "설정",
    notifications: "알림 설정",
    privacy: "개인정보 처리방침",
    customerService: "고객센터",
    logout: "로그아웃",
    version: "버전",

    // 홈 탭
    map: "지도",
    searchPlaceholder: "장소, 주소 검색",
    kakaoMapPlaceholder: "카카오 지도가 여기에 표시됩니다",
    kakaoMapNote: "실제 구현시 Kakao Map SDK 연동 필요",
    nearby: "내 주변",
    nearbySort: "가까운 순으로 정렬",

    // 커뮤니티 탭
    nearbyPosts: "내 주변",
    popularPosts: "인기순",
    writePost: "새 글 작성하기",

    // 파일 탭
    newFolder: "새 폴더",
    folderSearch: "폴더 검색",
    createFolder: "새 폴더 만들기",
    enterFolderName: "폴더 이름을 입력하세요",
    noSavedPlaces: "저장된 장소가 없습니다",
    saveFromMap: "지도에서 장소를 저장해보세요",
    addPlace: "장소 추가",
    places: "개 장소",
    createdDate: "생성일",
    savedDate: "저장일",
    backToFolders: "뒤로",

    // 마이페이지
    profileEdit: "프로필 편집",
    profileEditDesc: "프로필 사진, 이름, 소개 수정",
    settingsDesc: "알림, 언어, 테마 설정",
    notificationsDesc: "푸시 알림, 이메일 알림 관리",
    privacyDesc: "개인정보 보호 정책 확인",
    customerServiceDesc: "문의하기, 자주 묻는 질문",
    savedPlaces: "저장한 장소",
    posts: "작성한 글",
    likes: "받은 좋아요",
    followers: "팔로워",
    level: "레벨",
    explorer: "탐험가",

    // 설정
    appearance: "화면 설정",
    darkMode: "다크 모드",
    darkModeDesc: "어두운 테마 사용",
    languageRegion: "언어 및 지역",
    language: "언어",
    locationService: "위치 서비스",
    autoLocation: "자동 위치 감지",
    autoLocationDesc: "현재 위치를 자동으로 감지합니다",
    privacySecurity: "개인정보 및 보안",
    analytics: "사용 통계 전송",
    analyticsDesc: "앱 개선을 위한 익명 통계 전송",
    crashReports: "오류 보고서 전송",
    crashReportsDesc: "앱 오류 발생 시 자동 보고",
    accountManagement: "계정 관리",
    deleteAccount: "계정 삭제",
    deleteAccountDesc: "계정 삭제 시 모든 데이터가 영구적으로 삭제되며 복구할 수 없습니다",
    reset: "초기화",
    resetSettings: "앱 설정 초기화",
    resetDesc: "모든 설정이 기본값으로 복원됩니다",

    // 프로필 편집
    profilePhoto: "프로필 사진",
    uploadPhoto: "JPG, PNG 파일을 업로드하세요",
    changePhoto: "사진 변경",
    basicInfo: "기본 정보",
    name: "이름",
    username: "사용자명",
    usernameDesc: "다른 사용자들이 회원님을 찾을 때 사용됩니다",
    bio: "소개",
    bioPlaceholder: "자신을 소개해보세요",
    contactInfo: "연락처 정보",
    email: "이메일",
    phone: "전화번호",
    location: "지역",
    locationPlaceholder: "거주 지역을 입력하세요",

    // 알림 설정
    generalNotifications: "일반 알림",
    pushNotifications: "푸시 알림",
    pushNotificationsDesc: "앱 알림을 받습니다",
    emailNotifications: "이메일 알림",
    emailNotificationsDesc: "이메일로 알림을 받습니다",
    communityNotifications: "커뮤니티 알림",
    likeNotifications: "좋아요 알림",
    likeNotificationsDesc: "내 게시글에 좋아요가 달릴 때",
    commentNotifications: "댓글 알림",
    commentNotificationsDesc: "내 게시글에 댓글이 달릴 때",
    followNotifications: "팔로우 알림",
    followNotificationsDesc: "새로운 팔로워가 생길 때",
    locationNotifications: "위치 기반 알림",
    nearbyRecommendations: "주변 장소 추천",
    nearbyRecommendationsDesc: "새로운 주변 장소를 추천받습니다",
    locationUpdates: "위치 업데이트",
    locationUpdatesDesc: "위치 변경 시 알림을 받습니다",
    quietHours: "방해 금지 시간",
    quietMode: "방해 금지 모드",
    quietModeDesc: "지정된 시간에는 알림을 받지 않습니다",
    startTime: "시작 시간",
    endTime: "종료 시간",

    // 개인정보 처리방침
    privacyPolicyTitle: "개인정보 처리방침",

    // 고객센터
    customerServiceTitle: "고객센터",
    faq: "자주 묻는 질문",
    faqDesc: "빠른 해결책 찾기",
    contactUs: "문의하기",
    contactUsDesc: "직접 문의 작성",
    contactInfo: "연락처 정보",
    phoneSupport: "전화 상담",
    emailSupport: "이메일 문의",
    appInfo: "앱 정보",
    appVersion: "앱 버전",
    lastUpdate: "최근 업데이트",
    developer: "개발사",
    popularQuestions: "인기 질문",
    viewAllFaq: "전체 FAQ 보기",
    inquiryType: "문의 유형",
    selectInquiryType: "문의 유형을 선택하세요",
    bugReport: "버그 신고",
    featureRequest: "기능 제안",
    accountIssue: "계정 문제",
    other: "기타",
    title: "제목",
    titlePlaceholder: "문의 제목을 입력하세요",
    content: "내용",
    contentPlaceholder: "문의 내용을 자세히 작성해주세요",
    replyEmail: "답변 받을 이메일",
    replyEmailPlaceholder: "답변을 받을 이메일 주소",
    submitInquiry: "문의 제출",
  },
  en: {
    // Common
    home: "Home",
    community: "Community",
    files: "Files",
    mypage: "My Page",
    save: "Save",
    cancel: "Cancel",
    back: "Back",
    edit: "Edit",
    delete: "Delete",
    create: "Create",
    search: "Search",
    settings: "Settings",
    notifications: "Notifications",
    privacy: "Privacy Policy",
    customerService: "Customer Service",
    logout: "Logout",
    version: "Version",

    // Home Tab
    map: "Map",
    searchPlaceholder: "Search places, addresses",
    kakaoMapPlaceholder: "Kakao Map will be displayed here",
    kakaoMapNote: "Kakao Map SDK integration required for actual implementation",
    nearby: "Nearby",
    nearbySort: "Sorted by distance",

    // Community Tab
    nearbyPosts: "Nearby",
    popularPosts: "Popular",
    writePost: "Write New Post",

    // Files Tab
    newFolder: "New Folder",
    folderSearch: "Search folders",
    createFolder: "Create New Folder",
    enterFolderName: "Enter folder name",
    noSavedPlaces: "No saved places",
    saveFromMap: "Save places from the map",
    addPlace: "Add Place",
    places: " places",
    createdDate: "Created",
    savedDate: "Saved",
    backToFolders: "Back",

    // My Page
    profileEdit: "Edit Profile",
    profileEditDesc: "Edit profile photo, name, bio",
    settingsDesc: "Notifications, language, theme settings",
    notificationsDesc: "Manage push notifications, email notifications",
    privacyDesc: "View privacy protection policy",
    customerServiceDesc: "Contact us, frequently asked questions",
    savedPlaces: "Saved Places",
    posts: "Posts",
    likes: "Likes",
    followers: "Followers",
    level: "Level",
    explorer: "Explorer",

    // Settings
    appearance: "Appearance",
    darkMode: "Dark Mode",
    darkModeDesc: "Use dark theme",
    languageRegion: "Language & Region",
    language: "Language",
    locationService: "Location Service",
    autoLocation: "Auto Location",
    autoLocationDesc: "Automatically detect current location",
    privacySecurity: "Privacy & Security",
    analytics: "Send Analytics",
    analyticsDesc: "Send anonymous statistics for app improvement",
    crashReports: "Send Crash Reports",
    crashReportsDesc: "Automatically report app errors",
    accountManagement: "Account Management",
    deleteAccount: "Delete Account",
    deleteAccountDesc: "All data will be permanently deleted and cannot be recovered",
    reset: "Reset",
    resetSettings: "Reset App Settings",
    resetDesc: "All settings will be restored to default values",

    // Profile Edit
    profilePhoto: "Profile Photo",
    uploadPhoto: "Upload JPG, PNG files",
    changePhoto: "Change Photo",
    basicInfo: "Basic Information",
    name: "Name",
    username: "Username",
    usernameDesc: "Used by other users to find you",
    bio: "Bio",
    bioPlaceholder: "Introduce yourself",
    contactInfo: "Contact Information",
    email: "Email",
    phone: "Phone",
    location: "Location",
    locationPlaceholder: "Enter your location",

    // Notification Settings
    generalNotifications: "General Notifications",
    pushNotifications: "Push Notifications",
    pushNotificationsDesc: "Receive app notifications",
    emailNotifications: "Email Notifications",
    emailNotificationsDesc: "Receive notifications via email",
    communityNotifications: "Community Notifications",
    likeNotifications: "Like Notifications",
    likeNotificationsDesc: "When someone likes your post",
    commentNotifications: "Comment Notifications",
    commentNotificationsDesc: "When someone comments on your post",
    followNotifications: "Follow Notifications",
    followNotificationsDesc: "When you get new followers",
    locationNotifications: "Location-based Notifications",
    nearbyRecommendations: "Nearby Recommendations",
    nearbyRecommendationsDesc: "Get recommendations for nearby places",
    locationUpdates: "Location Updates",
    locationUpdatesDesc: "Get notified when location changes",
    quietHours: "Quiet Hours",
    quietMode: "Quiet Mode",
    quietModeDesc: "No notifications during specified hours",
    startTime: "Start Time",
    endTime: "End Time",

    // Privacy Policy
    privacyPolicyTitle: "Privacy Policy",

    // Customer Service
    customerServiceTitle: "Customer Service",
    faq: "FAQ",
    faqDesc: "Find quick solutions",
    contactUs: "Contact Us",
    contactUsDesc: "Write direct inquiry",
    contactInfo: "Contact Information",
    phoneSupport: "Phone Support",
    emailSupport: "Email Support",
    appInfo: "App Information",
    appVersion: "App Version",
    lastUpdate: "Last Update",
    developer: "Developer",
    popularQuestions: "Popular Questions",
    viewAllFaq: "View All FAQ",
    inquiryType: "Inquiry Type",
    selectInquiryType: "Select inquiry type",
    bugReport: "Bug Report",
    featureRequest: "Feature Request",
    accountIssue: "Account Issue",
    locationService: "Location Service",
    other: "Other",
    title: "Title",
    titlePlaceholder: "Enter inquiry title",
    content: "Content",
    contentPlaceholder: "Please describe your inquiry in detail",
    replyEmail: "Reply Email",
    replyEmailPlaceholder: "Email address to receive reply",
    submitInquiry: "Submit Inquiry",
  },
  ja: {
    // Common
    home: "ホーム",
    community: "コミュニティ",
    files: "ファイル",
    mypage: "マイページ",
    save: "保存",
    cancel: "キャンセル",
    back: "戻る",
    edit: "編集",
    delete: "削除",
    create: "作成",
    search: "検索",
    settings: "設定",
    notifications: "通知設定",
    privacy: "プライバシーポリシー",
    customerService: "カスタマーサービス",
    logout: "ログアウト",
    version: "バージョン",

    // Home Tab
    map: "地図",
    searchPlaceholder: "場所、住所を検索",
    kakaoMapPlaceholder: "ここにKakao地図が表示されます",
    kakaoMapNote: "実装時にKakao Map SDK連携が必要",
    nearby: "周辺",
    nearbySort: "距離順で並び替え",

    // Community Tab
    nearbyPosts: "周辺",
    popularPosts: "人気順",
    writePost: "新しい投稿を作成",

    // Files Tab
    newFolder: "新しいフォルダ",
    folderSearch: "フォルダ検索",
    createFolder: "新しいフォルダを作成",
    enterFolderName: "フォルダ名を入力してください",
    noSavedPlaces: "保存された場所がありません",
    saveFromMap: "地図から場所を保存してください",
    addPlace: "場所を追加",
    places: "個の場所",
    createdDate: "作成日",
    savedDate: "保存日",
    backToFolders: "戻る",

    // My Page
    profileEdit: "プロフィール編集",
    profileEditDesc: "プロフィール写真、名前、紹介を編集",
    settingsDesc: "通知、言語、テーマ設定",
    notificationsDesc: "プッシュ通知、メール通知の管理",
    privacyDesc: "プライバシー保護ポリシーを確認",
    customerServiceDesc: "お問い合わせ、よくある質問",
    savedPlaces: "保存した場所",
    posts: "投稿",
    likes: "いいね",
    followers: "フォロワー",
    level: "レベル",
    explorer: "エクスプローラー",

    // Settings
    appearance: "表示設定",
    darkMode: "ダークモード",
    darkModeDesc: "ダークテーマを使用",
    languageRegion: "言語と地域",
    language: "言語",
    locationService: "位置サービス",
    autoLocation: "自動位置検出",
    autoLocationDesc: "現在位置を自動的に検出します",
    privacySecurity: "プライバシーとセキュリティ",
    analytics: "使用統計の送信",
    analyticsDesc: "アプリ改善のための匿名統計を送信",
    crashReports: "エラーレポートの送信",
    crashReportsDesc: "アプリエラー発生時に自動報告",
    accountManagement: "アカウント管理",
    deleteAccount: "アカウント削除",
    deleteAccountDesc: "すべてのデータが永久に削除され、復元できません",
    reset: "リセット",
    resetSettings: "アプリ設定をリセット",
    resetDesc: "すべての設定がデフォルト値に復元されます",

    // Profile Edit
    profilePhoto: "プロフィール写真",
    uploadPhoto: "JPG、PNG ファイルをアップロード",
    changePhoto: "写真変更",
    basicInfo: "基本情報",
    name: "名前",
    username: "ユーザー名",
    usernameDesc: "他のユーザーがあなたを見つけるために使用されます",
    bio: "自己紹介",
    bioPlaceholder: "自己紹介をしてください",
    contactInfo: "連絡先情報",
    email: "メール",
    phone: "電話番号",
    location: "地域",
    locationPlaceholder: "お住まいの地域を入力してください",

    // Notification Settings
    generalNotifications: "一般通知",
    pushNotifications: "プッシュ通知",
    pushNotificationsDesc: "アプリ通知を受信します",
    emailNotifications: "メール通知",
    emailNotificationsDesc: "メールで通知を受信します",
    communityNotifications: "コミュニティ通知",
    likeNotifications: "いいね通知",
    likeNotificationsDesc: "投稿にいいねがついた時",
    commentNotifications: "コメント通知",
    commentNotificationsDesc: "投稿にコメントがついた時",
    followNotifications: "フォロー通知",
    followNotificationsDesc: "新しいフォロワーができた時",
    locationNotifications: "位置ベース通知",
    nearbyRecommendations: "周辺場所の推薦",
    nearbyRecommendationsDesc: "新しい周辺場所の推薦を受けます",
    locationUpdates: "位置更新",
    locationUpdatesDesc: "位置変更時に通知を受けます",
    quietHours: "サイレント時間",
    quietMode: "サイレントモード",
    quietModeDesc: "指定時間中は通知を受けません",
    startTime: "開始時間",
    endTime: "終了時間",

    // Privacy Policy
    privacyPolicyTitle: "プライバシーポリシー",

    // Customer Service
    customerServiceTitle: "カスタマーサービス",
    faq: "よくある質問",
    faqDesc: "迅速な解決策を見つける",
    contactUs: "お問い合わせ",
    contactUsDesc: "直接お問い合わせを作成",
    contactInfo: "連絡先情報",
    phoneSupport: "電話サポート",
    emailSupport: "メールサポート",
    appInfo: "アプリ情報",
    appVersion: "アプリバージョン",
    lastUpdate: "最終更新",
    developer: "開発者",
    popularQuestions: "人気の質問",
    viewAllFaq: "すべてのFAQを見る",
    inquiryType: "お問い合わせタイプ",
    selectInquiryType: "お問い合わせタイプを選択",
    bugReport: "バグ報告",
    featureRequest: "機能提案",
    accountIssue: "アカウント問題",
    locationService: "位置サービス",
    other: "その他",
    title: "タイトル",
    titlePlaceholder: "お問い合わせタイトルを入力",
    content: "内容",
    contentPlaceholder: "お問い合わせ内容を詳しく記載してください",
    replyEmail: "返信メール",
    replyEmailPlaceholder: "返信を受けるメールアドレス",
    submitInquiry: "お問い合わせ送信",
  },
  zh: {
    // Common
    home: "首页",
    community: "社区",
    files: "文件",
    mypage: "我的",
    save: "保存",
    cancel: "取消",
    back: "返回",
    edit: "编辑",
    delete: "删除",
    create: "创建",
    search: "搜索",
    settings: "设置",
    notifications: "通知设置",
    privacy: "隐私政策",
    customerService: "客服中心",
    logout: "退出登录",
    version: "版本",

    // Home Tab
    map: "地图",
    searchPlaceholder: "搜索地点、地址",
    kakaoMapPlaceholder: "Kakao地图将在此显示",
    kakaoMapNote: "实际实现需要Kakao Map SDK集成",
    nearby: "附近",
    nearbySort: "按距离排序",

    // Community Tab
    nearbyPosts: "附近",
    popularPosts: "热门",
    writePost: "写新帖子",

    // Files Tab
    newFolder: "新文件夹",
    folderSearch: "搜索文件夹",
    createFolder: "创建新文件夹",
    enterFolderName: "输入文件夹名称",
    noSavedPlaces: "没有保存的地点",
    saveFromMap: "从地图保存地点",
    addPlace: "添加地点",
    places: "个地点",
    createdDate: "创建日期",
    savedDate: "保存日期",
    backToFolders: "返回",

    // My Page
    profileEdit: "编辑资料",
    profileEditDesc: "编辑头像、姓名、简介",
    settingsDesc: "通知、语言、主题设置",
    notificationsDesc: "管理推送通知、邮件通知",
    privacyDesc: "查看隐私保护政策",
    customerServiceDesc: "联系我们、常见问题",
    savedPlaces: "保存的地点",
    posts: "帖子",
    likes: "点赞",
    followers: "关注者",
    level: "等级",
    explorer: "探索者",

    // Settings
    appearance: "外观设置",
    darkMode: "深色模式",
    darkModeDesc: "使用深色主题",
    languageRegion: "语言和地区",
    language: "语言",
    locationService: "位置服务",
    autoLocation: "自动定位",
    autoLocationDesc: "自动检测当前位置",
    privacySecurity: "隐私和安全",
    analytics: "发送使用统计",
    analyticsDesc: "发送匿名统计信息以改进应用",
    crashReports: "发送崩溃报告",
    crashReportsDesc: "应用错误时自动报告",
    accountManagement: "账户管理",
    deleteAccount: "删除账户",
    deleteAccountDesc: "所有数据将被永久删除且无法恢复",
    reset: "重置",
    resetSettings: "重置应用设置",
    resetDesc: "所有设置将恢复为默认值",

    // Profile Edit
    profilePhoto: "头像",
    uploadPhoto: "上传JPG、PNG文件",
    changePhoto: "更换照片",
    basicInfo: "基本信息",
    name: "姓名",
    username: "用户名",
    usernameDesc: "其他用户用来找到您",
    bio: "简介",
    bioPlaceholder: "介绍一下自己",
    contactInfo: "联系信息",
    email: "邮箱",
    phone: "电话",
    location: "地区",
    locationPlaceholder: "输入您的地区",

    // Notification Settings
    generalNotifications: "一般通知",
    pushNotifications: "推送通知",
    pushNotificationsDesc: "接收应用通知",
    emailNotifications: "邮件通知",
    emailNotificationsDesc: "通过邮件接收通知",
    communityNotifications: "社区通知",
    likeNotifications: "点赞通知",
    likeNotificationsDesc: "有人点赞您的帖子时",
    commentNotifications: "评论通知",
    commentNotificationsDesc: "有人评论您的帖子时",
    followNotifications: "关注通知",
    followNotificationsDesc: "有新关注者时",
    locationNotifications: "基于位置的通知",
    nearbyRecommendations: "附近推荐",
    nearbyRecommendationsDesc: "获取附近地点推荐",
    locationUpdates: "位置更新",
    locationUpdatesDesc: "位置变化时获得通知",
    quietHours: "免打扰时间",
    quietMode: "免打扰模式",
    quietModeDesc: "指定时间内不接收通知",
    startTime: "开始时间",
    endTime: "结束时间",

    // Privacy Policy
    privacyPolicyTitle: "隐私政策",

    // Customer Service
    customerServiceTitle: "客服中心",
    faq: "常见问题",
    faqDesc: "寻找快速解决方案",
    contactUs: "联系我们",
    contactUsDesc: "直接写询问",
    contactInfo: "联系信息",
    phoneSupport: "电话支持",
    emailSupport: "邮件支持",
    appInfo: "应用信息",
    appVersion: "应用版本",
    lastUpdate: "最后更新",
    developer: "开发者",
    popularQuestions: "热门问题",
    viewAllFaq: "查看所有FAQ",
    inquiryType: "询问类型",
    selectInquiryType: "选择询问类型",
    bugReport: "错误报告",
    featureRequest: "功能建议",
    accountIssue: "账户问题",
    locationService: "位置服务",
    other: "其他",
    title: "标题",
    titlePlaceholder: "输入询问标题",
    content: "内容",
    contentPlaceholder: "请详细描述您的询问",
    replyEmail: "回复邮箱",
    replyEmailPlaceholder: "接收回复的邮箱地址",
    submitInquiry: "提交询问",
  },
}

export function useLanguage() {
  const [currentLanguage, setCurrentLanguage] = useState("ko")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (language: string) => {
    if (translations[language]) {
      setCurrentLanguage(language)
      localStorage.setItem("language", language)
      // 강제로 페이지 새로고침하여 모든 컴포넌트가 새 언어로 렌더링되도록 함
      window.location.reload()
    }
  }

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || key
  }

  return { currentLanguage, changeLanguage, t }
}
